### ISSUE TITLE
Redesign Profile page

### ISSUE THREAD

**Issue by Akronix** [worona/worona-dashboard-layout#1]
Three separated tabs for such a small content is odd.
Profile page html should be rethought and redesigned.

**Comment by Poliuk** [comment]
If we are launching worona-dashboard (RFL) without "change password" and "change email" functionalities.  I think it doesn't make sense to program the profile page only for personal details (name, gender & location).

Once we add change password & email we can use this design or a new one.

We will get back here AFL.
