### ISSUE TITLE
We've to decide the errors to show when check site fail

### ISSUE THREAD

**Issue by rmartinezduque** [worona/worona-dashboard-layout#15]
I'd say something like this...

**If "Site online and available" fails:**

> ### Oops!
> 
> Looks like your site is not online or available. This may occur if:
> - You have entered an incorrect URL. Please make sure your site is correct: _http://www.site.com_. Want to fix it? Edit your URL [here](url).
> - Your WordPress website is down or it is too slow to respond.
>   Please [contact us](url) or try again later.

**If "Worona WordPress Plugin" fails:**

> ### WordPress Plugin missing
> 
> We can't find the Worona Plugin installed in your site. Our plugin lets you synchronize your WordPress site with our platform, please make sure it is installed and active.
> 
> [Install and activate Worona plugin now](url) or check out our [help documentation](url).

**Comment by Poliuk** [comment]
@rmartinezduque can you check this out?

[error 1](https://worona.github.io/worona-dashboard-layout/sites/site/checks-error.html)
[error 2](https://worona.github.io/worona-dashboard-layout/sites/site/checks-error-2.html)

If you think it's okey, we can take it to the dashboard repo. 

Pd. Help buttons will link to the specific help in https://docs.worona.org

**Comment by rmartinezduque** [comment]
I think it's fine 👍
