### ISSUE TITLE
Publish native: Redesign upload button to show it's dropzone too.

### ISSUE THREAD

**Issue by Akronix** [worona/worona-dashboard-layout#16]

**Comment by Poliuk** [comment]
@Akronix are you able to detect when the user is holding an image over the element? 

Let me know if you find this idea easy to implement:

- When user is holding an element over the box, we change the background to `background-color: #fff9cd`

- __uploading__: [publish-native-uploading](https://worona.github.io/worona-dashboard-layout/sites/site/publish-native-uploading.html)

- __success__:  [publish-native-success](https://worona.github.io/worona-dashboard-layout/sites/site/publish-native-success.html) _(back to normal colors after 5 seconds or user interaction)_

- __error__:  [publish-native-error](https://worona.github.io/worona-dashboard-layout/sites/site/publish-native-error.html)  _(back to normal colors after 5 seconds or user interaction)_

**Comment by Akronix** [comment]
@Poliuk Yes I am.

Done in https://github.com/worona/publish-native-app-extension-worona/commit/696bd3b0f1297bf9ff2521626a17765aef422939 and in https://github.com/worona/publish-native-app-extension-worona/commit/5c089350f2d3cca3af784924b1530b66c243670a
