### ISSUE TITLE
Modal to confirm the deletion of a site

### ISSUE THREAD

**Issue by Akronix** [worona/worona-dashboard-layout#25]

**Comment by Poliuk** [comment]
Cancel button and clicking outside the modal should close it. (removing the `is-active` class)

> Documentation [bulma modals](http://bulma.io/documentation/components/modal/)

**Comment by Poliuk** [comment]
**Design available here:** [sites-modal-delete.html](https://worona.github.io/worona-dashboard-layout/sites/sites-modal-delete.html)
