### ISSUE TITLE
Design /publish-native page

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-dashboard-layout#6]

**Comment by Poliuk** [comment]
Hey @rmartinezduque I've just uploaded a first version. We think that the layout is OK but probably we can improve the titles and add more text explaining every step in detail.

[Publish Native](https://worona.github.io/worona-dashboard-layout/sites/site/publish-native.html)

**Comment by rmartinezduque** [comment]
@Poliuk 

Ready to publish your mobile app? Here's what you should do next:

# 1. Create your app name and icon

Create a name and icon for your mobile app and let users easily identify it amongst other apps.

> ## **App name**
> 
> We recommend keeping your app name to around 12 characters or less. Long names may be truncated, which means users will not see all the characters.
> 
> ## **Icon**
> 
> This shall be a square image with at least 1024x1024px resolution. Try using your logo, or a unique shape or symbol to make your icon easily recognizable.

# 2. Preview

See what your icon and splash screen will look like before publishing.

> ## **Splash Screen**
> 
> This is the first image that is seen when your app is opened.
> 
> ## **App Icon**

# 3. Publish

Here you can choose whether you want to publish your app by yourself, or if you prefer us to do the work for you.

## **Do it yourself**

> Before starting, please note that you will need to:
> - Compile your apps using Phonegap Build and your own Adobe account.
> - Have an Apple developer account or create one, which costs 99€ a year.
> - Have a Google developer account or create one, which costs 35€.
> - Create the screenshots and fill all the required submission forms.
> - Upload your apps to the App Store and Google Play (you need a Mac to upload it to the App Store).
> 
> Whenever you're ready, download our .zip file below and check out our [Help Documentation](url), it will guide you through the next steps.
> 
> **Download**
> _This may take a while, please don't refresh the page._

## **Publish Pro Service**

> If you don’t want to deal with the process of publishing your app, let us take care of everything. 
> 
> With our **hassle-free** Publish Pro service you don’t need to compile your app or have any developer account. We’ll go through the whole submission process for you and upload your apps in Worona’s account, so you don’t have to pay Google or Apple to have your own account.
> 
> **Publish**
> _Questions or doubts? [Contact us](url) any time._

**Comment by Poliuk** [comment]
@rmartinezduque can you take a look now? I think the layout is much better. I've also added a help section below :)

[Publish Native](https://worona.github.io/worona-dashboard-layout/sites/site/publish-native.html)

**Comment by rmartinezduque** [comment]
@Poliuk Much better now! I'll correct a few things of the texts tomorrow, and it's done.

**Comment by luisherranz** [comment]
:+1::+1::+1:

**Comment by rmartinezduque** [comment]
# Any questions?

### Here are some answers.

## Is there a way to publish my apps to the App Stores for free?

> Unfortunately not. Apple and Google, owners of the Android & iOS App Stores, require you to have a developer account in order to submit your app. The price of these developer accounts is:
> 
> • Google Developer Account - $35 (one time fee)
> • Apple Developer Account - $99 per year
> 
> In addition, note that you'll need a Mac computer to upload the iOS app to the Stores.

## What does the Worona Publish Service include?

> Everything. With our hassle-free service you don’t need to compile your app or have any developer account. 
> 
> We’ll go through the whole submission process for you and upload your app in Worona’s account, so you don’t have to pay Google or Apple to have your own account. 
> 
> The price (290€ - one time payment) includes one mobile app for iOS and Android. With no extra fees. And you will have your app published in 5 - 7 working days.
> 
> Our [Publish Service](url) is the most convenient and simple way to submit your apps to the stores.

## What if I am not a developer, can I choose the Do It Yourself option?

> Yes, of course you can. But you should consider first that this is a technical and complex process.
> 
> We have worked hard to make Worona an easy platform ready to be used by everyone (not just developers). However, the submission of an app to the stores involves some technical knowledge and it can be a time-consuming process.
> 
> We encourage everybody to use [Phonegap Build](url). In addition there are lots of guides and tutorials on how to submit an .apk and .ipa files to the stores. But keep in mind that you will also need a Google and an Apple developer account, this costs more than $130 combined.
> 
> Lastly, your app will have to be approved by Google and Apple them to appear in their stores. Google usually takes 1 - 2 days to approve an app, while Apple may take 2 - 3 weeks.

## Is Phonegap Build free?

> Yes, it is. You can take advantage of Phonegap Build [free plan](url) to compile your app and get the .apk and .ipa files.
> 
> Afterwards you will need a Google and an Apple developer account to publish your app to the stores. Unfortunately these accounts are not free.
> 
> If you choose our [Worona Publish Service](url) you won’t have to worry about the Phonegap process or the developer accounts. We’ll take good care of your app.

## Have more questions? [Contact us](url).

**Comment by rmartinezduque** [comment]
@Poliuk Found one mistake, sorry! The last paragraph of the third answer should be:

> Lastly, your app will have to be approved by Google and Apple to appear in their stores. Google usually takes 1 - 2 days to approve an app, while Apple may take 2 - 3 weeks.
