### ISSUE TITLE
Design "loading" system

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-dashboard-layout#7]
We need a loading system to handle the following states:
- SPA loaded (JS ready and running in the client)
- SPA connected
- SPA logged in
- SPA subscriptions ready

Right now the user is being redirected to login and redirected back to the original page.

**Comment by Poliuk** [comment]
First version available here: https://worona.github.io/worona-dashboard-layout/sites/loading.html

**Comment by Poliuk** [comment]
The loader should also fit inside smaller sections that require to wait for the subscription to render.

Example: https://worona.github.io/worona-dashboard-layout/sites/site/loading-menu.html#

**Comment by luisherranz** [comment]
> https://worona.github.io/worona-dashboard-layout/sites/site/loading-menu.html#

You can't do that, the menu also needs the "settings" collection ready to be able to render itself because it needs to know the used extensions.

Maybe it's better to keep it always like this:
https://worona.github.io/worona-dashboard-layout/sites/loading.html
(without menu)

**Comment by luisherranz** [comment]
Looking again at this...
https://worona.github.io/worona-dashboard-layout/sites/loading.html

You are checking "connection" and "login" but show a "logged-in" screen, with sections like profile, licenses or even logout in the menu.

**Comment by Poliuk** [comment]
@luisherranz thanks for the feedback! Just changed the messages to avoid confusion. The [loading menu](https://worona.github.io/worona-dashboard-layout/sites/site/loading-menu.htm) is designed to be included when you are accessing a screen that only needs to retrieve data (connection and login are OK).

In the other cases we will still have the "login redirect glitch".
