### ISSUE TITLE
It's not clear when a Web App is served or activated

### ISSUE THREAD

**Issue by rmartinezduque** [worona/worona-dashboard-layout#8]
Once an app is configured you go to Publish and know the process is finished. It could be good to show the user once he clicks on 'Yes (serve the Web App)' that it is immediately served or activated.

**Comment by Poliuk** [comment]
Ey @rmartinezduque can you check if the new design is better? 

I've created a "Publish web App section": 
![screen shot 2016-10-20 at 20 11 29](https://cloud.githubusercontent.com/assets/2798729/19572165/69ed7fda-9701-11e6-904f-44da816d7dad.png)

In the new design the user has explicit feedback of the state of his webapp:

[Publish](https://worona.github.io/worona-dashboard-layout/sites/site/publish-webapp.html) -> [Publishing](https://worona.github.io/worona-dashboard-layout/sites/site/publish-webapp-loading.html) -> [Unpublish](https://worona.github.io/worona-dashboard-layout/sites/site/unpublish-webapp.html)

By the way, I need your help to write the messages above the action buttons.

**Comment by rmartinezduque** [comment]
I think these messages are clearer, but not sure if it will be too much info for you. Let me know what you think :)

**Publish webapp messages**:

> An HTML5 Web App allows you to serve an app-like version of your website running on mobile browsers. 
> 
> Once you click on ‘Publish’ it will be automatically displayed and visitors accessing your site from mobile browsers will see the Web App with the same look & feel of your Worona Native App.
> 
> Your WordPress Theme, Widgets & Plugins may not work inside the HTML5 Web App.
> 
> You can easily activate or deactivate this option as many times as necessary.

**Unpublish webapp messages**

> Once deactivated, visitors accessing your site from mobile browsers will see again your WordPress Theme.

**Comment by Poliuk** [comment]
Done :)
